name: vol-surface-project
channels:
  - defaults
  - conda-forge
dependencies:
  - flask
  - pip
  - pip:
    - yfinance
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - plotly
  - scipy
  - python = 3.13
  # Add other dependencies as needed
